#!/hpc/group/rekerlab/jwc81/conda/envs/molalkit/bin/python3.10
import sys
from molalkit.al.run import molalkit_run
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(molalkit_run())
